<<<<<<< HEAD
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
=======
import Header from "@/components/ui/Header"
import Footer from "@/components/ui/Footer"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body
        style={{
          margin: 0,
          fontFamily: "Arial, sans-serif",
          backgroundColor: "#f9fafb",
        }}
      >
        {/* 상단 네비게이션 */}
        <Header />

        {/* 메인 컨텐츠 */}
        <main style={{ minHeight: "80vh", padding: 20 }}>
          {children}
        </main>

        {/* 하단 (심사용 필수) */}
        <Footer />
      </body>
    </html>
  )
}
>>>>>>> c993a58d337638c1d437ecdc201e228e82c6d5e3
